
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Antonio Juan Vera
 * Created: 24-abr-2019
 */

/*DROP TABLE PERSONAJES;
DROP TABLE ARMAS;*/
DROP TABLE ARMAS;
DROP TABLE PERSONAJES;


CREATE TABLE PERSONAJES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(40),
    PASIVA VARCHAR(40),
    TACTICA VARCHAR(40),
    DEFINITIVA VARCHAR(40),
    CATEGORIA VARCHAR(40),
    CONSTRAINT ID_PERSONAJES_PK PRIMARY KEY (ID)
);

CREATE TABLE ARMAS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    PERSONAJES INTEGER NOT NULL,
    NOMBRE VARCHAR(40),
    CATEGORIA VARCHAR(40),
    MUNICIÓN VARCHAR(20),
    FECHAINCLUSION DATE,
    CARGADOR SMALLINT,
    CADENCIA DECIMAL(7,2),
    MODIFICABLE BOOLEAN,
    FOTO VARCHAR(30),
    CONSTRAINT ID_ARMAS_PK PRIMARY KEY (ID),
    CONSTRAINT PER_ARMAS_FK FOREIGN KEY (PERSONAJES) REFERENCES PERSONAJES (ID)
);